View - Social card1 visual design
openaustralia/publicwhip pull request #1347
Opened 2022-02-21 04:38 UTC by tseyiokorodudu

In this PR is the code responsible for social card 1 view. This includes the card haml and scss files along with an update to the members_controller file.

2022-02-21 23:31 UTC, mlandauer requested changes
Thanks for getting this PR together. I appreciate the work you've put into it. There are a few issues that it would be good to try to fix up before this is merged. None of them are particularly big things I think. The image size issue we can leave till after this PR.

Let me know if you have any questions or any of my feedback didn't make sense! :-)

2022-02-21 23:31 UTC, mlandauer commented on app/views/card/policy_with_member_card.html.haml
> +    window.addEventListener('DOMContentLoaded', (event) => {
I think some comments in the code here to say why this javascript code is here and what is doing would be good

2022-02-21 23:31 UTC, mlandauer commented on app/views/layouts/card_layout.html.haml
> +    - if Settings.facebook_admins
Does this need to be here? As you're using a separate layout for the card then there's no reason to have this facebook stuff here.

2022-02-21 23:31 UTC, mlandauer commented on app/views/layouts/card_layout.html.haml
> +    <!--[if lt IE 9]>
The IE support is just needed as the only browser that's going to need to see this in the specific browser that's doing the screenshotting

2022-02-21 23:31 UTC, mlandauer commented on app/assets/stylesheets/card/_card.scss
> +        width: 150px;
This is upscaling the image beyond its natural size so it's going to be blocky. For the purposes of this PR leave it as is but I do think we need to tackle that properly after this gets merged and figure out a pipeline for getting higher resolution images.

2022-02-21 23:31 UTC, mlandauer commented on app/views/card/policy_with_member_card.html.haml
> +                    %img{:src => @member.large_image_url}
You can use the more modern ruby 1.9 syntax here `%img{src: @member.large_image_url}`

2022-02-21 23:35 UTC, mlandauer commented
I'm not sure why the CI (travis) didn't run over this PR. Hmmm..

2022-02-22 03:49 UTC, tseyiokorodudu commented on app/controllers/members_controller.rb
> +    @link_to_policy = "How is this worked out? #{request.original_url}"
Currently working on this.

2022-02-22 23:42 UTC, mlandauer commented
LGTM! Thanks @tseyiokorodudu 🎉

2022-02-22 23:42 UTC, merged

2022-02-23 00:11 UTC, mlandauer commented
This is now rolled out to production. I had to fix up a couple of things - it turned out the javascript compressor used in production wasn't setup to support ES6 syntax. That was config change in a2218169ca4a354518aa9c965219ff37ebd6693a. Also the change to move the javascript to its own assets file had to be reverted because it was actually getting included in the main `application.js` and so was running on every page causing errors.